# Generated by Django 4.2.23 on 2025-08-11 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_management', '0004_alter_cmg_unique_together_alter_cmg_cmg_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_name', models.CharField(help_text='故障名称', max_length=128)),
                ('fault_level', models.IntegerField(default=1, help_text='故障等级(1-5)')),
                ('component', models.CharField(blank=True, help_text='涉及部件', max_length=128)),
                ('description', models.TextField(blank=True, help_text='故障描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cmg_model', models.ForeignKey(help_text='关联的CMG模型', on_delete=django.db.models.deletion.CASCADE, related_name='fault_definitions', to='data_management.cmgmodel')),
            ],
            options={
                'verbose_name': '故障定义',
                'verbose_name_plural': '故障定义',
                'unique_together': {('cmg_model', 'fault_name')},
            },
        ),
        migrations.CreateModel(
            name='RuleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(help_text='规则ID', max_length=64)),
                ('rule_expression', models.TextField(help_text='规则表达式')),
                ('source', models.CharField(choices=[('expert', '专家意见'), ('data_driven', '数据驱动挖掘')], default='expert', help_text='规则来源', max_length=20)),
                ('plan_description', models.TextField(blank=True, help_text='预案描述')),
                ('is_online', models.BooleanField(default=True, help_text='是否在线启用')),
                ('is_new', models.BooleanField(default=True, help_text='是否为新规则')),
                ('is_editable', models.BooleanField(default=True, help_text='是否可编辑')),
                ('related_parameters', models.JSONField(default=list, help_text='涉及的参数列表')),
                ('compiled_rule', models.JSONField(blank=True, help_text='编译后的规则', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cmg_model', models.ForeignKey(help_text='关联的CMG模型', on_delete=django.db.models.deletion.CASCADE, related_name='rule_definitions', to='data_management.cmgmodel')),
                ('fault_definition', models.ForeignKey(help_text='关联的故障定义', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rule_detection.faultdefinition')),
            ],
            options={
                'verbose_name': '规则定义',
                'verbose_name_plural': '规则定义',
                'unique_together': {('cmg_model', 'rule_id')},
            },
        ),
        migrations.CreateModel(
            name='RuleDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_triggered', models.BooleanField(help_text='规则是否被触发')),
                ('confidence_score', models.FloatField(help_text='置信度分数')),
                ('detection_details', models.JSONField(default=dict, help_text='检测详细信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_point', models.ForeignKey(help_text='关联的数据点', on_delete=django.db.models.deletion.CASCADE, related_name='rule_results', to='data_management.cmgdata')),
                ('fault_definition', models.ForeignKey(help_text='检测到的故障', on_delete=django.db.models.deletion.CASCADE, related_name='detection_results', to='rule_detection.faultdefinition')),
                ('rule_definition', models.ForeignKey(help_text='触发的规则', on_delete=django.db.models.deletion.CASCADE, related_name='detection_results', to='rule_detection.ruledefinition')),
            ],
            options={
                'verbose_name': '规则检测结果',
                'verbose_name_plural': '规则检测结果',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(help_text='组件名称', max_length=128)),
                ('description', models.TextField(blank=True, help_text='组件描述')),
                ('parameters', models.JSONField(default=list, help_text='关联的参数列表')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cmg_model', models.ForeignKey(help_text='关联的CMG模型', on_delete=django.db.models.deletion.CASCADE, related_name='component_definitions', to='data_management.cmgmodel')),
            ],
            options={
                'verbose_name': '组件定义',
                'verbose_name_plural': '组件定义',
                'unique_together': {('cmg_model', 'component_name')},
            },
        ),
    ]
