# Generated by Django 4.2.23 on 2025-08-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ruledetectionresult',
            index=models.Index(fields=['-created_at'], name='rule_detect_created_5f8c84_idx'),
        ),
        migrations.AddIndex(
            model_name='ruledetectionresult',
            index=models.Index(fields=['is_triggered'], name='rule_detect_is_trig_c57602_idx'),
        ),
        migrations.AddIndex(
            model_name='ruledetectionresult',
            index=models.Index(fields=['data_point', 'created_at'], name='rule_detect_data_po_087c42_idx'),
        ),
    ]
