# Generated by Django 4.2.23 on 2025-08-18 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='登出时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='会话密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('login_method', models.CharField(default='web', help_text='登录方式：web(网页), api(接口), mobile(移动端)', max_length=20, verbose_name='登录方式')),
                ('device_info', models.JSONField(blank=True, default=dict, verbose_name='设备信息')),
                ('location_info', models.JSONField(blank=True, default=dict, verbose_name='位置信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户登录记录',
                'verbose_name_plural': '用户登录记录',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['-login_time'], name='users_userl_login_t_32b757_idx'), models.Index(fields=['user', '-login_time'], name='users_userl_user_id_2d5c2b_idx'), models.Index(fields=['is_active'], name='users_userl_is_acti_b325ce_idx')],
            },
        ),
    ]
