# Generated by Django 4.2.23 on 2025-08-18 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userloginrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('page_visited', models.CharField(max_length=100, verbose_name='访问页面')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='会话密钥')),
                ('device_info', models.JSONField(blank=True, default=dict, verbose_name='设备信息')),
                ('access_duration', models.IntegerField(default=0, verbose_name='访问时长(秒)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户访问记录',
                'verbose_name_plural': '用户访问记录',
                'ordering': ['-access_time'],
            },
        ),
        migrations.DeleteModel(
            name='UserLoginRecord',
        ),
        migrations.AddIndex(
            model_name='useraccessrecord',
            index=models.Index(fields=['-access_time'], name='users_usera_access__e8a590_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccessrecord',
            index=models.Index(fields=['user', '-access_time'], name='users_usera_user_id_1e8a93_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccessrecord',
            index=models.Index(fields=['page_visited'], name='users_usera_page_vi_0753da_idx'),
        ),
    ]
