# Generated by Django 4.2.23 on 2025-08-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraccessrecord_delete_userloginrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', '绠＄悊鍛?), ('user', '鏅€氱敤鎴?)], default='user', help_text='Role of the user for permission management', max_length=16),
        ),
    ]

