# Generated by Django 4.2.23 on 2025-08-09 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PHM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmg_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this PHM is currently enabled for monitoring')),
            ],
            options={
                'verbose_name': 'PHM',
                'verbose_name_plural': 'PHMs',
            },
        ),
        migrations.CreateModel(
            name='PHMType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('TCP', 'TCP缃戠粶瀵煎叆'), ('FILE', '鏈湴鏂囦欢瀵煎叆')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('protocol_description', models.TextField(blank=True, help_text='Network protocol description (editable)', null=True)),
                ('file', models.FileField(blank=True, help_text='Uploaded data file when the method is FILE', null=True, upload_to='imports/%Y/%m/%d')),
                ('cmg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sessions', to='data_management.cmg')),
            ],
            options={
                'verbose_name': 'Import session',
                'verbose_name_plural': 'Import sessions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PHMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('cmg_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.cmgtype')),
            ],
        ),
        migrations.AddField(
            model_name='cmg',
            name='cmg_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cmgs', to='data_management.cmgmodel'),
        ),
        migrations.AddField(
            model_name='cmg',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmgs', to='data_management.satellite'),
        ),
        migrations.CreateModel(
            name='PHMData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Data timestamp')),
                ('data', models.JSONField(help_text='Raw or parsed telemetry content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cmg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='data_management.cmg')),
                ('import_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='data_management.importsession')),
            ],
            options={
                'verbose_name': 'PHM data',
                'verbose_name_plural': 'PHM data',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['cmg', 'timestamp'], name='data_manage_cmg_id_e3ed18_idx')],
                'unique_together': {('cmg', 'timestamp')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cmg',
            unique_together={('satellite', 'cmg_id')},
        ),
    ]

