# Generated by Django 4.2.23 on 2025-08-09 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_cmgdata_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmgmodel',
            name='cmg_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.cmgtype'),
        ),
    ]
