# Generated by Django 4.2.23 on 2025-08-09 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_alter_cmgmodel_cmg_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cmg',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cmg',
            name='cmg_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cmg',
            name='satellite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmgs', to='data_management.satellite'),
        ),
    ]
