# Generated by Django 4.2.23 on 2025-08-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0004_alter_cmg_unique_together_alter_cmg_cmg_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='完成时间', null=True),
        ),
        migrations.AddField(
            model_name='importsession',
            name='detection_summary',
            field=models.JSONField(blank=True, default=dict, help_text='检测结果摘要'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='error_message',
            field=models.TextField(blank=True, help_text='错误信息', null=True),
        ),
        migrations.AddField(
            model_name='importsession',
            name='failed_records',
            field=models.IntegerField(default=0, help_text='失败记录数'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='processed_records',
            field=models.IntegerField(default=0, help_text='已处理记录数'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='processing_progress',
            field=models.FloatField(default=0.0, help_text='处理进度百分比'),
        ),
        migrations.AddField(
            model_name='importsession',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', '待处理'), ('PARSING', '解析中'), ('STORING', '存储中'), ('DETECTING', '检测中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', help_text='文件处理状态', max_length=20),
        ),
        migrations.AddField(
            model_name='importsession',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='开始处理时间', null=True),
        ),
        migrations.AddField(
            model_name='importsession',
            name='total_records',
            field=models.IntegerField(default=0, help_text='总记录数'),
        ),
    ]
