# Generated by Django 4.2.23 on 2025-08-18 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0005_add_import_session_progress_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('cmg_data', 'PHM閬ユ祴鏁版嵁'), ('ims_results', 'IMS妫€娴嬬粨鏋?), ('rule_results', '瑙勫垯妫€娴嬬粨鏋?), ('msfg_results', 'MSFG妫€娴嬬粨鏋?), ('anomaly_frames', '寮傚父甯?), ('total_frames', '鎬诲抚鏁?)], max_length=20, verbose_name='缁熻绫诲瀷')),
                ('count', models.BigIntegerField(default=0, verbose_name='鏁伴噺')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='鏈€鍚庢洿鏂版椂闂?)),
                ('cmg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management.cmg', verbose_name='PHM')),
            ],
            options={
                'verbose_name': '鏁版嵁搴撶粺璁?,
                'verbose_name_plural': '鏁版嵁搴撶粺璁?,
                'unique_together': {('stat_type', 'cmg')},
            },
        ),
    ]

