# Generated by Django 4.2.23 on 2025-08-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0006_databasestatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='max_rows',
            field=models.IntegerField(blank=True, help_text='最大处理行数，null表示处理整个文件', null=True),
        ),
    ]
