# Generated by Django 4.2.23 on 2025-08-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0007_add_max_rows_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='import_mode',
            field=models.CharField(choices=[('IMPORT_AND_DETECT', '导入并检测'), ('IMPORT_ONLY', '仅导入')], default='IMPORT_AND_DETECT', help_text='导入模式：仅导入或导入并检测', max_length=20),
        ),
    ]
