# Generated by Django 4.2.23 on 2025-08-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0008_add_import_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='add_milliseconds',
            field=models.BooleanField(default=True, help_text='是否自动为重复时间戳添加毫秒'),
        ),
    ]
