# Generated by Django 4.2.30 on 2026-09-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phm', '0002_acceptancetelemetry_alarmrule_auditevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrysession',
            name='monitoring_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RealtimeAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('threshold', models.FloatField()),
                ('operator', models.CharField(max_length=4)),
                ('severity', models.CharField(default='warning', max_length=20)),
                ('fault_name', models.CharField(max_length=200)),
                ('isolation_target', models.CharField(max_length=200)),
                ('health_index', models.FloatField(default=1.0)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='phm.telemetrysample')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='phm.telemetrysession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='realtimealarm',
            constraint=models.UniqueConstraint(fields=('sample', 'signal'), name='unique_realtime_sample_signal_alarm'),
        ),
    ]
