# Generated by Django 4.2.30 on 2026-09-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phm', '0003_telemetrysession_monitoring_enabled_realtimealarm_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='realtimealarm',
            name='unique_realtime_sample_signal_alarm',
        ),
        migrations.AddConstraint(
            model_name='realtimealarm',
            constraint=models.UniqueConstraint(fields=('sample', 'signal', 'operator', 'threshold'), name='unique_realtime_sample_rule_alarm'),
        ),
    ]
