# Generated by Django 4.2.23 on 2025-08-09 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyResult',
            fields=[
                ('data_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='anomaly_result', serialize=False, to='data_management.cmgdata')),
                ('score', models.FloatField(help_text='Overall anomaly score')),
                ('parameter_scores', models.JSONField(blank=True, default=dict, help_text='Per-parameter anomaly scores')),
                ('is_anomaly', models.BooleanField(default=False, help_text='Whether this record is anomalous')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Anomaly result',
                'verbose_name_plural': 'Anomaly results',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('graph_definition', models.JSONField(help_text='Definition of the multi-signal flow graph')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cmg_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_graphs', to='data_management.cmgmodel')),
            ],
            options={
                'verbose_name': 'Diagnosis graph',
                'verbose_name_plural': 'Diagnosis graphs',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, help_text='Human readable description of the rule')),
                ('definition', models.JSONField(help_text='Machine readable rule definition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cmg_model', models.ForeignKey(help_text='PHM model this rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='data_management.cmgmodel')),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.CreateModel(
            name='LifePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='When the prediction was computed')),
                ('predicted_end_time', models.DateTimeField(help_text="Predicted time when the PHM's health reaches zero")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cmg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_predictions', to='data_management.cmg')),
            ],
            options={
                'verbose_name': 'Life prediction',
                'verbose_name_plural': 'Life predictions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HealthEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('score', models.FloatField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cmg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_evaluations', to='data_management.cmg')),
            ],
            options={
                'verbose_name': 'Health evaluation',
                'verbose_name_plural': 'Health evaluations',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RuleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_triggered', models.BooleanField()),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context about the evaluation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_results', to='health_management.anomalyresult')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='health_management.rule')),
            ],
            options={
                'verbose_name': 'Rule result',
                'verbose_name_plural': 'Rule results',
                'unique_together': {('anomaly', 'rule')},
            },
        ),
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.JSONField(help_text='Structured diagnosis result')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_results', to='health_management.anomalyresult')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='health_management.diagnosisgraph')),
            ],
            options={
                'verbose_name': 'Diagnosis result',
                'verbose_name_plural': 'Diagnosis results',
                'unique_together': {('anomaly', 'graph')},
            },
        ),
    ]

