# Generated by Django 4.2.23 on 2025-08-10 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0004_alter_cmg_unique_together_alter_cmg_cmg_id_and_more'),
        ('health_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='妯″瀷鍚嶇О', max_length=128)),
                ('parameters', models.JSONField(help_text='鐩戞祴鍙傛暟鍒楄〃')),
                ('model_config', models.JSONField(help_text='妯″瀷閰嶇疆')),
                ('model_data', models.BinaryField(help_text='搴忓垪鍖栫殑妯″瀷鏁版嵁')),
                ('threshold', models.FloatField(help_text='寮傚父闃堝€?)),
                ('is_active', models.BooleanField(default=True, help_text='鏄惁婵€娲?)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cmg_model', models.ForeignKey(help_text='PHM妯″瀷', on_delete=django.db.models.deletion.CASCADE, related_name='ims_models', to='data_management.cmgmodel')),
            ],
            options={
                'verbose_name': 'IMS妯″瀷',
                'verbose_name_plural': 'IMS妯″瀷',
            },
        ),
        migrations.CreateModel(
            name='IMSDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anomaly', models.BooleanField(help_text='鏄惁寮傚父')),
                ('anomaly_score', models.FloatField(help_text='寮傚父鍒嗘暟')),
                ('parameter_scores', models.JSONField(default=dict, help_text='鍚勫弬鏁板紓甯稿垎鏁?)),
                ('detection_details', models.JSONField(default=dict, help_text='妫€娴嬭缁嗕俊鎭?)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_point', models.OneToOneField(help_text='瀵瑰簲鐨勬暟鎹偣', on_delete=django.db.models.deletion.CASCADE, related_name='ims_result', to='data_management.cmgdata')),
                ('ims_model', models.ForeignKey(help_text='浣跨敤鐨処MS妯″瀷', on_delete=django.db.models.deletion.CASCADE, related_name='detection_results', to='health_management.imsmodel')),
            ],
            options={
                'verbose_name': 'IMS妫€娴嬬粨鏋?,
                'verbose_name_plural': 'IMS妫€娴嬬粨鏋?,
                'ordering': ['-created_at'],
            },
        ),
    ]

