# Generated by Django 4.2.30 on 2026-09-14 10:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaultWorkflowTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mode', models.CharField(choices=[('offline', 'offline'), ('realtime', 'realtime')], max_length=20)),
                ('subsystem', models.CharField(max_length=100)),
                ('fault_mode', models.CharField(max_length=100)),
                ('severity', models.FloatField(default=0.5)),
                ('injection_time', models.FloatField(default=20)),
                ('status', models.CharField(default='created', max_length=30)),
                ('current_stage', models.CharField(default='created', max_length=30)),
                ('dataset_id', models.IntegerField(blank=True, null=True)),
                ('latest_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaultWorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('timestamp', models.FloatField()),
                ('stage', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='simulation_demo.faultworkflowtask')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('task', 'sequence')},
            },
        ),
    ]
