# Generated by Django 4.2.23 on 2025-08-11 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_management', '0004_alter_cmg_unique_together_alter_cmg_cmg_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSFGDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='MSFG名称', max_length=128)),
                ('description', models.TextField(blank=True, help_text='MSFG描述')),
                ('raw_graph_data', models.JSONField(help_text='原始图数据')),
                ('processed_graph_data', models.JSONField(help_text='处理后的图数据')),
                ('detection_matrix', models.JSONField(blank=True, help_text='检测矩阵', null=True)),
                ('test_names', models.JSONField(default=list, help_text='测试点名称列表')),
                ('fault_names', models.JSONField(default=list, help_text='故障名称列表')),
                ('component_names', models.JSONField(default=list, help_text='组件名称列表')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cmg_model', models.ForeignKey(help_text='关联的CMG模型', on_delete=django.db.models.deletion.CASCADE, related_name='msfg_definitions', to='data_management.cmgmodel')),
            ],
            options={
                'verbose_name': '多信号流图定义',
                'verbose_name_plural': '多信号流图定义',
                'unique_together': {('cmg_model', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MSFGNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(help_text='节点ID', max_length=64)),
                ('node_type', models.CharField(choices=[('test', '测试点'), ('fault', '故障点'), ('system', '系统节点'), ('component', '组件节点')], help_text='节点类型', max_length=20)),
                ('name', models.CharField(help_text='节点名称', max_length=128)),
                ('position_x', models.FloatField(default=0, help_text='X坐标')),
                ('position_y', models.FloatField(default=0, help_text='Y坐标')),
                ('properties', models.JSONField(default=dict, help_text='节点属性')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('msfg_definition', models.ForeignKey(help_text='关联的MSFG定义', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='msfg_analysis.msfgdefinition')),
            ],
            options={
                'verbose_name': 'MSFG节点',
                'verbose_name_plural': 'MSFG节点',
                'unique_together': {('msfg_definition', 'node_id')},
            },
        ),
        migrations.CreateModel(
            name='MSFGAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_results', models.JSONField(default=dict, help_text='测试点结果')),
                ('fault_results', models.JSONField(default=dict, help_text='故障点结果')),
                ('system_results', models.JSONField(default=dict, help_text='系统分析结果')),
                ('overall_health_score', models.FloatField(default=1.0, help_text='总体健康分数')),
                ('detected_faults', models.JSONField(default=list, help_text='检测到的故障列表')),
                ('analysis_details', models.JSONField(default=dict, help_text='分析详细信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_point', models.ForeignKey(help_text='关联的数据点', on_delete=django.db.models.deletion.CASCADE, related_name='msfg_results', to='data_management.cmgdata')),
                ('msfg_definition', models.ForeignKey(help_text='使用的MSFG定义', on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='msfg_analysis.msfgdefinition')),
            ],
            options={
                'verbose_name': 'MSFG分析结果',
                'verbose_name_plural': 'MSFG分析结果',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MSFGEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_id', models.CharField(help_text='边ID', max_length=64)),
                ('edge_type', models.CharField(blank=True, help_text='边类型', max_length=64)),
                ('properties', models.JSONField(default=dict, help_text='边属性')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('msfg_definition', models.ForeignKey(help_text='关联的MSFG定义', on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='msfg_analysis.msfgdefinition')),
                ('source_node', models.ForeignKey(help_text='源节点', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='msfg_analysis.msfgnode')),
                ('target_node', models.ForeignKey(help_text='目标节点', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='msfg_analysis.msfgnode')),
            ],
            options={
                'verbose_name': 'MSFG边',
                'verbose_name_plural': 'MSFG边',
                'unique_together': {('msfg_definition', 'edge_id')},
            },
        ),
    ]
