# Generated by Django 4.2 on 2025-08-14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0004_alter_cmg_unique_together_alter_cmg_cmg_id_and_more'),
        ('rule_detection', '0001_initial'),
        ('msfg_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPointRuleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(help_text='测试点名称', max_length=128)),
                ('weight', models.FloatField(default=1.0, help_text='权重（可选）')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cmg_model', models.ForeignKey(help_text='关联的CMG模型', on_delete=django.db.models.deletion.CASCADE, related_name='msfg_testpoint_mappings', to='data_management.cmgmodel')),
                ('rule_definition', models.ForeignKey(help_text='关联的规则定义', on_delete=django.db.models.deletion.CASCADE, related_name='msfg_testpoint_mappings', to='rule_detection.ruledefinition')),
            ],
            options={
                'verbose_name': '规则-测试点映射',
                'verbose_name_plural': '规则-测试点映射',
                'unique_together': {('cmg_model', 'rule_definition')},
            },
        ),
    ]


