# Generated by Django 4.2.23 on 2025-08-15 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0005_add_import_session_progress_fields'),
        ('msfg_analysis', '0002_testpoint_rule_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(help_text='测试点名称', max_length=128)),
                ('rule_id', models.CharField(help_text='规则ID', max_length=64)),
                ('rule_expression', models.TextField(help_text='规则表达式（单点表达式）')),
                ('weight', models.FloatField(default=1.0, help_text='权重（0..10）')),
                ('is_online', models.BooleanField(default=True, help_text='是否启用')),
                ('description', models.TextField(blank=True, help_text='规则描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cmg_model', models.ForeignKey(help_text='关联的CMG模型', on_delete=django.db.models.deletion.CASCADE, related_name='msfg_testpoint_rules', to='data_management.cmgmodel')),
            ],
            options={
                'verbose_name': 'MSFG测点规则',
                'verbose_name_plural': 'MSFG测点规则',
                'unique_together': {('cmg_model', 'test_name', 'rule_id')},
            },
        ),
    ]
