# Generated by Django 4.2.23 on 2025-08-16 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msfg_analysis', '0005_update_testpoint_rule_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpointrule',
            name='msfg_definition',
            field=models.ForeignKey(blank=True, help_text='关联的MSFG定义', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testpoint_rules', to='msfg_analysis.msfgdefinition'),
        ),
    ]
