# Generated by Django 4.2.23 on 2025-08-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0005_add_import_session_progress_fields'),
        ('msfg_analysis', '0006_make_msfg_definition_optional'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testpointrule',
            unique_together={('cmg_model', 'test_name', 'rule_id')},
        ),
    ]
