# Generated by Django 4.2.23 on 2025-08-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msfg_analysis', '0007_update_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpointcomponentmapping',
            name='mapping_type',
            field=models.CharField(choices=[('one_to_one', '一对一'), ('one_to_many', '一对多'), ('many_to_one', '多对一')], default='one_to_one', help_text='映射类型', max_length=20),
        ),
        migrations.AddField(
            model_name='testpointcomponentmapping',
            name='weight',
            field=models.FloatField(default=1.0, help_text='权重（0.1-10）'),
        ),
    ]
