# Generated by Django 4.2.23 on 2025-08-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msfg_analysis', '0008_testpointcomponentmapping_mapping_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testpointcomponentmapping',
            unique_together={('msfg_definition', 'test_point_name', 'component_name')},
        ),
    ]
