# Generated by Django 4.2.23 on 2025-08-18 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msfg_analysis', '0009_alter_testpointcomponentmapping_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultComponentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_name', models.CharField(help_text='故障名称', max_length=128)),
                ('component_name', models.CharField(help_text='部件名称', max_length=128)),
                ('mapping_type', models.CharField(choices=[('one_to_one', '一对一'), ('one_to_many', '一对多'), ('many_to_one', '多对一')], default='one_to_one', help_text='映射类型', max_length=20)),
                ('weight', models.FloatField(default=1.0, help_text='权重（0.1-10）')),
                ('is_critical', models.BooleanField(default=False, help_text='是否为关键映射')),
                ('description', models.TextField(blank=True, help_text='映射描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('msfg_definition', models.ForeignKey(help_text='关联的MSFG定义', on_delete=django.db.models.deletion.CASCADE, related_name='fault_component_mappings', to='msfg_analysis.msfgdefinition')),
            ],
            options={
                'verbose_name': '故障-部件映射',
                'verbose_name_plural': '故障-部件映射',
                'unique_together': {('msfg_definition', 'fault_name', 'component_name')},
            },
        ),
    ]
