<template>
  <div class="page alarm-page">
    <div class="page-head"><div><span>PHM MONITOR / ALERT CENTER</span><h2>异常告警中心</h2><p>只展示当前仿真场景已经触发的告警，告警来源与仿真结果保持一致。</p></div><el-button type="primary" :loading="loading" @click="runDemo">重新运行仿真</el-button></div>
    <el-card class="scenario" shadow="never"><div class="scenario-title">仿真场景</div><el-form inline><el-form-item label="子系统"><el-select v-model="subsystem" @change="mode = modeOptions[0]" style="width:150px"><el-option v-for="x in Object.keys(modeMap)" :key="x" :label="x" :value="x" /></el-select></el-form-item><el-form-item label="故障模式"><el-select v-model="mode" style="width:190px"><el-option v-for="x in modeOptions" :key="x" :label="x" :value="x" /></el-select></el-form-item><el-form-item label="严重度"><el-slider v-model="severity" :min="0.1" :max="1" :step="0.1" style="width:180px" /></el-form-item></el-form></el-card>
    <div class="stats"><el-card shadow="never"><small>当前告警</small><strong class="danger">{{ alarms.length }}</strong><span>当前场景</span></el-card><el-card shadow="never"><small>最高等级</small><strong>{{ alarms.length ? alarms[0].level : '正常' }}</strong><span>{{ alarms.length ? '需关注' : '未发现异常' }}</span></el-card><el-card shadow="never"><small>健康指数</small><strong>{{ last ? last.health_index : '—' }}</strong><span>{{ last ? '仿真计算值' : '等待运行' }}</span></el-card></div>
    <el-card shadow="never" class="result"><template #header><div class="card-title"><b>当前场景告警</b><el-tag :type="last?.alarm ? 'danger' : 'success'">{{ last?.alarm ? '已触发' : '运行正常' }}</el-tag></div></template><el-alert v-if="last" :title="last.alarm ? `${mode}：检测到 1 条有效告警` : '当前仿真数据未触发告警'" :type="last.alarm ? 'error' : 'success'" show-icon :closable="false" /><el-empty v-if="!alarms.length" description="当前场景没有告警" /><el-table v-else :data="alarms" stripe><el-table-column prop="level" label="等级" width="90"><template #default="s"><el-tag type="danger">{{ s.row.level }}</el-tag></template></el-table-column><el-table-column prop="location" label="告警位置" width="180"/><el-table-column prop="cause" label="告警原因"/><el-table-column prop="evidence" label="检测依据"/><el-table-column prop="suggestion" label="建议处置"/></el-table></el-card>
  </div>
</template>
<script setup>
import { ref, computed, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
const modeMap = { 动力: ['泄漏', '泵效率下降'], 控制: ['传感器偏置', '执行器迟滞'] }
const subsystem = ref('动力'), mode = ref('泄漏'), severity = ref(0.7), loading = ref(false), last = ref(null), alarms = ref([])
const modeOptions = computed(() => modeMap[subsystem.value])
const descriptions = { 泄漏: ['推进剂供给管路', '管路压力持续下降', '压力低于 7.55 MPa'], '泵效率下降': ['燃料泵', '泵效率持续衰减', '发动机温度趋势异常'], 传感器偏置: ['姿态传感器', '测量零点出现固定偏移', '姿态误差超过阈值'], 执行器迟滞: ['姿态执行器', '控制指令响应迟滞', '控制误差持续增大'] }
async function runDemo() { loading.value = true; try { const r = await fetch('/api/v1/simulation-demo/run/', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fault: { subsystem: subsystem.value, mode: mode.value, severity: severity.value, start: 20 } }) }); const d = await r.json(); if (!r.ok) throw Error(d.error || '检测失败'); last.value = d.summary; alarms.value = d.diagnosis.alarm ? [{ level: severity.value >= .8 ? '高' : '中', location: descriptions[mode.value][0], cause: descriptions[mode.value][1], evidence: `健康指数 ${d.summary.health_index}，${descriptions[mode.value][2]}`, suggestion: '隔离异常通道并进入故障诊断' }] : []; ElMessage.success('仿真检测完成') } catch (e) { ElMessage.error(e.message) } finally { loading.value = false } }
onMounted(runDemo)
</script>
<style scoped>.page{max-width:1280px}.page-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:18px}.page-head span{color:#1677ff;font-size:12px;letter-spacing:1px}.page-head h2{margin:8px 0}.page-head p{color:#718198;margin:0}.scenario{margin-bottom:16px}.scenario-title{font-weight:600;margin-bottom:12px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:16px}.stats strong{display:block;font-size:28px;margin:5px 0}.stats span,.stats small{color:#718198;font-size:13px}.danger{color:#e34d59}.result .card-title{display:flex;justify-content:space-between;align-items:center}.el-alert{margin-bottom:16px}@media(max-width:700px){.page-head{display:block}.page-head .el-button{margin-top:14px}.stats{grid-template-columns:1fr}}</style>
