<template>
  <div class="page">
    <div class="head"><div><span>PHM STRUCTURE / PBS</span><h2>运载器结构树管理</h2><p>整机、分系统、子系统、单机产品四层 PBS 隶属关系模板，可按实际型号继续编辑。</p></div><div><el-button @click="expandAll">全部展开</el-button><el-button @click="collapseAll">全部收起</el-button></div></div>
    <el-card shadow="never" class="search"><el-input v-model="keyword" clearable placeholder="搜索名称、节点标识或 PBS 编码" @keyup.enter="search"><template #append><el-button @click="search">查询</el-button></template></el-input><el-tag type="info">共 {{nodes.length}} 个节点</el-tag></el-card>
    <div class="workspace">
      <el-card shadow="never" class="tree-card"><template #header><div class="card-head"><b>运载器 PBS 结构树</b><el-button type="primary" @click="openCreate(null)">新增根节点</el-button></div></template><el-empty v-if="!tree.length" description="暂无结构树模板"/><el-tree v-else ref="treeRef" :data="tree" node-key="id" :props="treeProps" :filter-node-method="filterNode" :expand-on-click-node="false" default-expand-all highlight-current @node-click="select"><template #default="{data}"><div class="tree-node"><div class="identity"><el-tag size="small" :type="typeStyle[data.node_type]">{{typeLabels[data.node_type]}}</el-tag><span class="name">{{data.name}}</span><code>{{data.pbs_code}}</code></div><div class="node-actions"><el-button v-if="data.node_type!=='product'" link type="primary" @click.stop="openCreate(data)">新增下级</el-button><el-button link @click.stop="openEdit(data)">编辑/移动</el-button><el-button link type="danger" @click.stop="remove(data)">删除</el-button></div></div></template></el-tree></el-card>
      <el-card shadow="never" class="detail-card"><template #header><b>节点信息</b></template><el-empty v-if="!current" description="请在左侧选择节点"/><el-descriptions v-else :column="1" border><el-descriptions-item label="节点标识">{{current.node_key}}</el-descriptions-item><el-descriptions-item label="节点名称">{{current.name}}</el-descriptions-item><el-descriptions-item label="节点层级">{{typeLabels[current.node_type]}}</el-descriptions-item><el-descriptions-item label="PBS 编码">{{current.pbs_code}}</el-descriptions-item><el-descriptions-item label="父节点标识">{{parentOf(current)?.node_key||'—（根节点）'}}</el-descriptions-item><el-descriptions-item label="所属父节点">{{parentOf(current)?.name||'—（整机根节点）'}}</el-descriptions-item></el-descriptions><div v-if="current" class="detail-actions"><el-button type="primary" @click="openEdit(current)">编辑节点</el-button><el-button v-if="current.node_type!=='product'" @click="openCreate(current)">新增下级</el-button></div></el-card>
    </div>
    <el-dialog v-model="dialog" :title="editing?'编辑结构节点':'新增结构节点'" width="560px"><el-form :model="form" label-width="110px"><el-form-item label="节点标识" required><el-input v-model="form.node_key" :disabled="editing" placeholder="例如 prod-main-engine"/></el-form-item><el-form-item label="节点名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="节点层级" required><el-select v-model="form.node_type" :disabled="!!fixedType"><el-option v-for="(label,key) in typeLabels" :key="key" :label="label" :value="key"/></el-select></el-form-item><el-form-item label="PBS 编码" required><el-input v-model="form.pbs_code" placeholder="例如 RLV-01-01-01"/></el-form-item><el-form-item label="所属父节点"><el-tree-select v-model="form.parent_id" :data="parentOptions" check-strictly clearable node-key="id" :props="treeProps" placeholder="运载器根节点无父节点"/></el-form-item></el-form><el-alert title="层级固定为：运载器 → 分系统 → 子系统 → 单机产品" type="info" :closable="false"/><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import{ref,computed,onMounted,watch}from'vue';import{ElMessage,ElMessageBox}from'element-plus'
const tree=ref([]),nodes=ref([]),treeRef=ref(),keyword=ref(''),loading=ref(false),saving=ref(false),dialog=ref(false),editing=ref(null),current=ref(null),fixedType=ref('');const form=ref({node_key:'',name:'',node_type:'vehicle',pbs_code:'',parent_id:null});const treeProps={label:'name',children:'children'};const typeLabels={vehicle:'运载器',system:'分系统',subsystem:'子系统',product:'单机产品'},typeStyle={vehicle:'danger',system:'warning',subsystem:'success',product:'info'},nextType={vehicle:'system',system:'subsystem',subsystem:'product'}
async function api(url,options={}){const r=await fetch(url,{credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const j=await r.json();if(!r.ok)throw Error(j.error||j.detail||`请求失败 ${r.status}`);return j}
async function load(){loading.value=true;try{const j=await api('/api/v1/phm/acceptance/structure/');tree.value=j.tree||[];nodes.value=j.results||[];if(current.value)current.value=nodes.value.find(x=>x.id===current.value.id)||null}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}
function select(data){current.value=data}function parentOf(node){return nodes.value.find(x=>x.id===node.parent_id)}
function openCreate(parent){editing.value=null;fixedType.value=parent?nextType[parent.node_type]:'vehicle';form.value={node_key:'',name:'',node_type:fixedType.value,pbs_code:parent?`${parent.pbs_code}-`: 'RLV',parent_id:parent?.id||null};dialog.value=true}
function openEdit(node){editing.value=node;fixedType.value='';form.value={node_key:node.node_key,name:node.name,node_type:node.node_type,pbs_code:node.pbs_code,parent_id:node.parent_id};dialog.value=true}
const parentOptions=computed(()=>{if(!form.value.node_type||form.value.node_type==='vehicle')return[];const allowed={system:'vehicle',subsystem:'system',product:'subsystem'}[form.value.node_type];function prune(list){return list.filter(x=>x.node_type===allowed).map(x=>({...x,children:prune(x.children||[])}))}return prune(tree.value)})
async function save(){if(!form.value.node_key||!form.value.name||!form.value.pbs_code)return ElMessage.warning('请填写节点标识、名称和 PBS 编码');saving.value=true;try{const url=editing.value?`/api/v1/phm/acceptance/structure/${editing.value.id}/`:'/api/v1/phm/acceptance/structure/';await api(url,{method:editing.value?'PATCH':'POST',body:JSON.stringify(form.value)});dialog.value=false;await load();ElMessage.success('结构树已保存')}catch(e){ElMessage.error(e.message)}finally{saving.value=false}}
async function remove(node){try{await ElMessageBox.confirm(`确认删除“${node.name}”及其全部下级节点？`,'删除结构节点',{type:'warning'});await api(`/api/v1/phm/acceptance/structure/${node.id}/?cascade=true`,{method:'DELETE'});if(current.value?.id===node.id)current.value=null;await load();ElMessage.success('节点已删除')}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error(e.message)}}
function filterNode(value,data){if(!value)return true;const k=value.toLowerCase();return`${data.name} ${data.node_key} ${data.pbs_code}`.toLowerCase().includes(k)}function search(){treeRef.value?.filter(keyword.value)}watch(keyword,search);function expandAll(){nodes.value.forEach(x=>treeRef.value?.store.nodesMap[x.id]?.expand())}function collapseAll(){nodes.value.forEach(x=>treeRef.value?.store.nodesMap[x.id]?.collapse())}onMounted(load)
</script>
<style scoped>.page{max-width:1450px}.head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:18px}.head span{font-size:12px;color:#1677ff;letter-spacing:1px}.head h2{margin:8px 0}.head p{margin:0;color:#718198}.search{margin-bottom:16px}.search :deep(.el-card__body){display:flex;gap:16px;align-items:center}.search .el-input{max-width:520px}.workspace{display:grid;grid-template-columns:minmax(620px,1.6fr) minmax(340px,.8fr);gap:16px}.card-head,.tree-node{display:flex;justify-content:space-between;align-items:center}.tree-card :deep(.el-tree-node__content){height:46px;border-bottom:1px solid #eef1f5}.tree-card :deep(.el-tree-node__children){border-left:1px solid #d9e1ea;margin-left:12px}.tree-node{width:100%;padding-right:8px}.identity{display:flex;align-items:center;gap:10px}.identity .name{font-weight:600;color:#26384f}.identity code{font-size:12px;color:#66809c;background:#edf3f8;padding:3px 7px;border-radius:4px}.node-actions{opacity:.25;transition:.2s}.tree-node:hover .node-actions{opacity:1}.detail-actions{margin-top:18px}.el-select{width:100%}.el-alert{margin-top:10px}@media(max-width:1000px){.workspace{grid-template-columns:1fr}.head{display:block}.head>div:last-child{margin-top:12px}.node-actions{opacity:1}}</style>
