<template>
  <div class="overview">
    <section class="hero"><div><span class="eyebrow">REUSABLE LAUNCH VEHICLE HEALTH MANAGEMENT PLATFORM</span><h2>综合健康态势</h2><p>监测、诊断、评估、预测与仿真统一工作台</p></div><el-button type="primary" :loading="loading" @click="loadStatus">刷新平台状态</el-button></section>
    <section class="panel"><header><div><h3>PHM能力链</h3><p>平台核心业务闭环</p></div><el-tag type="success">{{ readyCount }}/4 项已接入</el-tag></header><div class="chain"><div v-for="(c,i) in capabilities" :key="c.key" class="chain-item"><div class="step">0{{i+1}}</div><strong>{{c.name}}</strong><span>{{c.desc}}</span><el-tag size="small" :type="c.type">{{c.status}}</el-tag><el-button v-if="c.path" link type="primary" @click="$router.push(c.path)">进入模块 →</el-button></div></div></section>
    <section class="panel services"><header><div><h3>服务与数据状态</h3><p>实时检查后端算法和仿真数据</p></div></header><div class="service-grid"><div><span>故障诊断 Hier14</span><b :class="diag?'ok':'warn'" :title="diagError">{{diag?'已加载':'未启用'}}</b></div><div><span>健康评估适配器</span><b :class="health?'ok':'warn'">{{health?'已加载':'未启用'}}</b></div><div><span>RUL Shadow模型</span><b class="warn">已登记（开发）</b></div><div><span>仿真数据 / MATLAB</span><b :class="simulation?'ok':'warn'">{{simulation?'已配置':'待配置'}}</b></div></div><el-alert v-if="!diag && diagError" :title="`Hier14 加载原因：${diagError}`" type="warning" :closable="false" style="margin-top:14px" /></section>
  </div>
</template>
<script setup>
import {ref,computed,onMounted} from 'vue';import{ElMessage}from'element-plus';
const loading=ref(false),diag=ref(false),health=ref(false),simulation=ref(false),diagError=ref('');
const capabilities=computed(()=>[{key:'monitor',name:'状态监测',desc:'多源遥测与趋势',status:'框架就绪',type:'success',path:'/telemetry'},{key:'diag',name:'故障诊断',desc:'Hier14 14类诊断模型',status:diag.value?'已接入（开发）':'演示可用',type:'success',path:'/fault-diagnosis'},{key:'health',name:'平台算法评估',desc:'系统健康度与告警',status:health.value?'已接入（开发）':'演示可用',type:'success',path:'/platform-health'},{key:'rul',name:'寿命预测',desc:'RUL及不确定性区间',status:'演示可用',type:'success',path:'/lifetime-prediction'}]);
const readyCount=computed(()=>[true,diag.value,health.value,true].filter(Boolean).length);
async function loadStatus(){loading.value=true;try{const [dr,hr,sr]=await Promise.all([fetch('/api/v1/fault-diagnosis/status/'),fetch('/api/v1/health-assessment/status/'),fetch('/api/v1/phm/status/')]);const [d,h,s]=await Promise.all([dr.json(),hr.json(),sr.json()]);diag.value=!!d.available;diagError.value=d.error||'';health.value=!!h.available;simulation.value=!!s.simulation_data_loaded;if(!d.available&&d.error) ElMessage.warning(`Hier14 未启用：${d.error}`);else ElMessage.success('平台状态已更新')}catch(e){diagError.value=e.message;ElMessage.error('状态读取失败')}finally{loading.value=false}}onMounted(loadStatus)
</script>
<style scoped>.overview{padding:0}.hero{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.eyebrow{color:#2782e8;font-size:11px;font-weight:700;letter-spacing:1.5px}.hero h2{font-size:25px;margin:7px 0;color:#192d45}.hero p,.panel header p{margin:0;color:#8593a6;font-size:13px}.panel{background:#fff;border:1px solid #e7ebf1;border-radius:11px;box-shadow:0 5px 20px #18385b0a;padding:20px;margin-bottom:18px}.panel header{display:flex;justify-content:space-between;border-bottom:1px solid #edf0f4;padding-bottom:14px;margin-bottom:16px}.panel h3{margin:0 0 5px;font-size:18px}.chain{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.chain-item{background:#f7f9fc;border:1px solid #e9edf3;border-radius:9px;padding:16px}.step{font-size:11px;color:#3789e6;font-weight:800}.chain-item strong,.chain-item span{display:block}.chain-item strong{margin:8px 0 5px;font-size:17px}.chain-item span{height:32px;color:#7d8ca0;font-size:13px}.chain-item .el-button{display:block;padding-left:0;margin-top:8px}.service-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:0 30px}.service-grid div{display:flex;justify-content:space-between;padding:13px 0;border-bottom:1px dashed #e6eaf0;font-size:14px}.service-grid b{font-weight:500}.ok{color:#17a878}.warn{color:#d28a35}@media(max-width:900px){.chain{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.chain,.service-grid{grid-template-columns:1fr}}
</style>
