<template>
  <div>
    <section class="hero">
      <div><span class="eyebrow">SPACECRAFT PHM / SYSTEM OVERVIEW</span><h2>综合健康态势</h2><p>面向可重复使用航天器的监测、诊断、评估与预测统一工作台</p></div>
      <el-button type="primary" @click="refresh"><el-icon><Refresh /></el-icon>刷新平台状态</el-button>
    </section>
    <div class="metrics">
      <div v-for="item in metrics" :key="item.label" class="metric"><div class="metric-icon" :style="{background:item.bg,color:item.color}"><el-icon><component :is="item.icon" /></el-icon></div><div><small>{{item.label}}</small><strong>{{item.value}}</strong><span>{{item.note}}</span></div></div>
    </div>
    <div class="grid">
      <section class="panel span2"><header><div><h3>PHM能力链</h3><p>平台核心业务闭环</p></div><el-tag type="info">能力链状态</el-tag></header><div class="chain"><div v-for="(c,i) in capabilities" :key="c.name" class="chain-item"><div class="step">0{{i+1}}</div><strong>{{c.name}}</strong><span>{{c.desc}}</span><el-tag size="small" :type="c.type">{{c.status}}</el-tag></div></div></section>
      <section class="panel"><header><div><h3>系统运行状态</h3><p>基础服务连通性</p></div><span class="online">● 在线</span></header><div class="services"><div><span>Django API</span><b class="ok">正常</b></div><div><span>算法服务</span><b>待接入</b></div><div><span>仿真数据</span><b>待接入</b></div><div><span>数据库</span><b class="ok">SQLite</b></div></div></section>
      <section class="panel span2"><header><div><h3>重点监测对象</h3><p>材料要求对应的典型分系统</p></div><el-button text type="primary">结构管理 →</el-button></header><div class="systems"><div v-for="s in systems" :key="s.name"><i :class="s.level"></i><div><strong>{{s.name}}</strong><span>{{s.detail}}</span></div><em>{{s.state}}</em></div></div></section>
      <section class="panel"><header><div><h3>近期告警</h3><p>实时异常与处置状态</p></div><el-badge :value="0" /></header><div class="empty"><el-icon><CircleCheck /></el-icon><strong>暂无告警</strong><span>仿真/遥测数据接入后显示</span></div></section>
    </div>
  </div>
</template>
<script setup>
import { ref } from 'vue'; import { ElMessage } from 'element-plus'; import { Refresh, Monitor, Warning, TrendCharts, Timer, CircleCheck } from '@element-plus/icons-vue';
const metrics=[{label:'部件档案',value:'49',note:'已接入部件档案',icon:Monitor,bg:'#e7f2ff',color:'#287bea'},{label:'FMECA记录',value:'13',note:'典型故障模式',icon:Warning,bg:'#fff3e5',color:'#ee8a24'},{label:'综合健康度',value:'—',note:'等待在线评估',icon:TrendCharts,bg:'#e8fbf4',color:'#16a678'},{label:'模型资产',value:'202',note:'已登记、待验证',icon:Timer,bg:'#f0ebff',color:'#7654d8'}];
const capabilities=[{name:'状态监测',desc:'多源遥测与趋势',status:'框架就绪',type:'success'},{name:'故障诊断',desc:'规则、MSFG与智能诊断',status:'算法服务未启用',type:'warning'},{name:'健康评估',desc:'部件HI与系统健康度',status:'算法服务未启用',type:'warning'},{name:'寿命预测',desc:'RUL及不确定性区间',status:'算法服务未启用',type:'warning'}];
const systems=[{name:'推进系统',detail:'发动机、泵阀与管路',state:'未接入',level:'blue'},{name:'电源系统',detail:'电池、配电与供电链路',state:'未接入',level:'green'},{name:'航电系统',detail:'飞控、导航与通信设备',state:'未接入',level:'purple'}];
const refresh=async()=>{try{await fetch('/api/v1/phm/status/');ElMessage.success('平台服务正常')}catch{ElMessage.error('平台服务不可用')}};
</script>
<style scoped>
.hero{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.eyebrow{color:#2782e8;font-size:11px;font-weight:700;letter-spacing:1.5px}.hero h2{font-size:25px;margin:7px 0;color:#192d45}.hero p,.panel header p{margin:0;color:#8593a6;font-size:13px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:18px}.metric,.panel{background:#fff;border:1px solid #e7ebf1;border-radius:11px;box-shadow:0 5px 20px #18385b0a}.metric{padding:18px;display:flex;gap:14px;align-items:center}.metric-icon{width:46px;height:46px;border-radius:10px;display:grid;place-items:center;font-size:22px}.metric small,.metric span{display:block;color:#8997a9;font-size:12px}.metric strong{display:block;font-size:24px;margin:3px 0}.grid{display:grid;grid-template-columns:2fr 1fr;gap:18px}.panel{padding:20px}.span2{grid-column:auto}.panel header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:1px solid #edf0f4;padding-bottom:14px;margin-bottom:16px}.panel h3{margin:0 0 5px;font-size:16px}.chain{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.chain-item{position:relative;background:#f7f9fc;border:1px solid #e9edf3;border-radius:9px;padding:14px}.step{font-size:11px;color:#3789e6;font-weight:800}.chain-item strong,.chain-item span{display:block}.chain-item strong{margin:8px 0 5px}.chain-item span{height:34px;color:#7d8ca0;font-size:12px}.services div{display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px dashed #e6eaf0;font-size:13px}.services b{color:#a1abba}.services .ok,.online{color:#17a878}.systems{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.systems>div{display:flex;align-items:center;gap:10px;border:1px solid #e8edf3;border-radius:9px;padding:14px}.systems i{width:8px;height:36px;border-radius:5px;background:#348bea}.systems i.green{background:#20ad82}.systems i.purple{background:#8065df}.systems strong,.systems span{display:block}.systems span{font-size:12px;color:#8996a7;margin-top:4px}.systems em{margin-left:auto;font-style:normal;font-size:12px;color:#9aa5b4}.empty{text-align:center;padding:18px;color:#8e9bad}.empty .el-icon{display:block;margin:auto;font-size:38px;color:#2abc90}.empty strong,.empty span{display:block;margin-top:8px}.empty span{font-size:12px}@media(max-width:1100px){.metrics{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}.chain{grid-template-columns:repeat(2,1fr)}}
</style>
