<template><div class="platform-health"><h1>平台健康评估</h1><p>提交窗口级健康证据并查看算法结果。</p><el-alert v-if="status.error" :title="status.error" type="warning"/><el-card><el-input v-model="payload" type="textarea" :rows="10"/><div class="actions"><el-button type="primary" :loading="loading" @click="evaluate">评估当前记录</el-button><el-button :loading="loading" @click="evaluateBatch">批量评估</el-button><el-button @click="reset">重置会话</el-button></div><p>必填字段：run_id、component_id、window_index、timestamp、hi_cd、hi_ae、anomaly_score。</p></el-card><el-card v-if="result"><el-descriptions :column="2" border><el-descriptions-item label="部件">{{result.component_id}}</el-descriptions-item><el-descriptions-item label="健康指数">{{result.component_hi}}</el-descriptions-item><el-descriptions-item label="健康状态">{{result.degradation_state}}</el-descriptions-item><el-descriptions-item label="告警状态">{{result.fault_alarm_status}}</el-descriptions-item><el-descriptions-item label="定位状态">{{result.localization_status}}</el-descriptions-item><el-descriptions-item label="Trace hash">{{result.trace_hash}}</el-descriptions-item></el-descriptions><pre>{{JSON.stringify(result,null,2)}}</pre></el-card></div></template>
<script setup>
import {onMounted,ref} from 'vue';import {ElMessage} from 'element-plus'
const payload=ref(JSON.stringify({run_id:9001,session_id:'web',component_id:'lox_pump',window_index:0,timestamp:144.9,hi_cd:.96,hi_ae:1,anomaly_score:-7.5,confidence:.97},null,2));const result=ref(null);const loading=ref(false);const status=ref({})
async function req(path,body){const r=await fetch(`/api/v1/health-assessment/${path}/`,{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d}
async function evaluate(){loading.value=true;try{result.value=(await req('evaluate',JSON.parse(payload.value))).result}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}
async function evaluateBatch(){loading.value=true;try{result.value=(await req('batch',{lines:JSON.parse(payload.value)})).results?.[0]}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}
async function reset(){try{await req('reset',{});result.value=null;ElMessage.success('会话已重置')}catch(e){ElMessage.error(e.message)}}
onMounted(async()=>{try{status.value=await(await fetch('/api/v1/health-assessment/status/')).json()}catch(e){status.value={error:e.message}}})
</script><style scoped>.platform-health{padding:24px;max-width:1100px}.platform-health h1{margin-bottom:8px}.platform-health .el-card{margin-top:18px}.actions{display:flex;gap:12px;margin:16px 0;flex-wrap:wrap}pre{white-space:pre-wrap;background:#f6f8fa;padding:12px}</style>
