<template>
  <div class="page">
    <div class="head"><div><span>REFLIGHT & RELEASE</span><h2>再飞可行性与发射放行评估</h2><p>根据各分系统健康度、用户配置权重、寿命裕度和严重告警，计算整器级放行辅助结论。</p></div><el-tag type="warning">最终结论须人工签署</el-tag></div>
    <el-alert class="formula" type="info" :closable="false" show-icon><template #title>评估计算逻辑</template>系统健康指数 = 65% × 加权健康度 + 35% × RBD 等效健康度；任务成功概率还会考虑寿命裕度、严重告警和再飞模型证据。</el-alert>
    <div class="grid">
      <el-card shadow="never"><template #header><b>评估输入与权重配置</b></template><el-form label-width="132px">
        <el-form-item label="运载器编号"><el-input v-model="form.vehicle_id" /></el-form-item><el-form-item label="任务名称"><el-input v-model="form.mission_name" /></el-form-item>
        <el-divider content-position="left">分系统健康度与权重</el-divider><div class="hint">健康度表示当前模块状态（0～100 分）；权重表示该模块在整器评估中的重要程度。后端会归一化权重。</div>
        <div v-for="item in subsystems" :key="item.key" class="subsystem-row"><div class="subsystem-title"><b>{{item.key}}</b><el-tooltip :content="item.desc"><el-icon><InfoFilled /></el-icon></el-tooltip></div><div class="input-line"><span>健康度</span><el-slider v-model="item.percent" :min="0" :max="100" show-input /></div><div class="input-line weight-line"><span>权重</span><el-input-number v-model="item.weight" :min="0" :max="1" :step=".01" :precision="2" controls-position="right" /><small>归一化 {{normalizedWeight(item.key)}}%</small></div></div>
        <div class="weight-summary"><span>当前权重合计：<b :class="weightTotalValid?'ok':'bad'">{{weightTotal}}%</b></span><el-button link type="primary" @click="resetWeights">恢复默认权重</el-button></div>
        <el-divider content-position="left">放行判据</el-divider>
        <el-form-item label="寿命裕度"><el-slider v-model="rulPercent" :min="0" :max="100" show-input /></el-form-item><div class="param-help">预计剩余寿命或可复用裕度，越低会降低任务成功概率。</div>
        <el-form-item label="严重告警"><el-input-number v-model="form.open_critical_alarms" :min="0" :max="20" /></el-form-item><div class="param-help">未关闭严重告警数量；每条都会降低成功概率并形成阻断项。</div>
        <el-form-item label="放行阈值"><el-input-number v-model="form.release_threshold" :min=".5" :max=".99" :step=".01" :precision="2" /></el-form-item><div class="param-help">成功概率达到此值且不存在其他阻断项时，给出“建议放行”。</div>
        <el-form-item label="子系统最低阈值"><el-input-number v-model="form.minimum_subsystem_hi" :min="0" :max="1" :step=".01" :precision="2" /></el-form-item><div class="param-help">任一模块健康度低于此值，会直接形成放行阻断项。</div>
        <el-button type="primary" :loading="loading" :disabled="!weightTotalValid" @click="run">执行放行评估</el-button>
      </el-form></el-card>
      <el-card shadow="never"><template #header><b>评估结论</b></template><el-empty v-if="!result" description="等待执行评估" /><template v-else><div :class="['decision',result.decision]"><small>辅助决策</small><strong>{{result.decision_label}}</strong><span>任务成功概率 {{pct(result.mission_success_probability)}}</span></div><el-progress type="dashboard" :percentage="Math.round(result.mission_success_probability*100)" :status="result.decision==='release'?'success':'exception'" /><el-descriptions border :column="2"><el-descriptions-item label="系统健康指数">{{result.system_health_index}}</el-descriptions-item><el-descriptions-item label="加权健康度">{{result.weighted_health_index}}</el-descriptions-item><el-descriptions-item label="RBD等效健康">{{result.rbd_equivalent_health}}</el-descriptions-item><el-descriptions-item label="使用权重">{{weightText(result.subsystem_weights)}}</el-descriptions-item><el-descriptions-item label="放行阈值">{{result.release_threshold}}</el-descriptions-item><el-descriptions-item label="最低子系统阈值">{{result.minimum_subsystem_hi}}</el-descriptions-item><el-descriptions-item label="VAE重构误差">{{modelResult?.reconstruction_error?.toFixed(6)??'—'}}</el-descriptions-item><el-descriptions-item label="RF健康概率">{{modelResult?pct(modelResult.rf_probability):'—'}}</el-descriptions-item><el-descriptions-item label="模型状态" :span="2">{{modelStatus}}</el-descriptions-item></el-descriptions><el-alert v-if="result.blockers.length" title="放行阻断项" type="error" :closable="false"><template #default><ul><li v-for="x in result.blockers" :key="x">{{x}}</li></ul></template></el-alert><el-alert v-else title="所有判据均已通过" type="success" :closable="false" /><p class="note">加权健康度和 RBD 为工程基线；VAE-GAN/RF 仅作为模型证据，最终放行须由授权人员签署。</p></template></el-card>
    </div>
    <el-card shadow="never" class="history"><template #header><b>最近评估记录</b></template><el-table :data="history"><el-table-column prop="created_at" label="时间"><template #default="s">{{new Date(s.row.created_at).toLocaleString()}}</template></el-table-column><el-table-column prop="vehicle_id" label="运载器" /><el-table-column prop="mission_name" label="任务" /><el-table-column prop="mission_success_probability" label="成功概率"><template #default="s">{{pct(s.row.mission_success_probability)}}</template></el-table-column><el-table-column prop="decision_label" label="结论"><template #default="s"><el-tag :type="s.row.decision==='release'?'success':'danger'">{{s.row.decision_label}}</el-tag></template></el-table-column></el-table></el-card>
  </div>
</template>
<script setup>
import{computed,onMounted,ref}from'vue';import{ElMessage}from'element-plus';import{InfoFilled}from'@element-plus/icons-vue'
const DEFAULT_WEIGHTS={动力:.32,电源:.26,测控:.16,导航制导与控制:.16,结构:.10}
const subsystems=ref([{key:'动力',percent:93,weight:.32,desc:'发动机、推进剂供应和推力链路，直接影响动力输出。'},{key:'电源',percent:91,weight:.26,desc:'蓄电池、配电和母线供电能力。'},{key:'测控',percent:90,weight:.16,desc:'遥测、遥控、通信和地面测控链路。'},{key:'导航制导与控制',percent:92,weight:.16,desc:'导航、制导、姿态控制和执行机构。'},{key:'结构',percent:95,weight:.10,desc:'箭体、贮箱、承力和热防护结构。'}])
const form=ref({vehicle_id:'RLV-DEMO-01',mission_name:'重复使用运载器发射任务',open_critical_alarms:0,release_threshold:.85,minimum_subsystem_hi:.65}),rulPercent=ref(90),loading=ref(false),result=ref(),history=ref([])
const rawWeightTotal=computed(()=>subsystems.value.reduce((s,x)=>s+Number(x.weight||0),0)),weightTotal=computed(()=>Math.round(rawWeightTotal.value*100)),weightTotalValid=computed(()=>rawWeightTotal.value>0&&Math.abs(rawWeightTotal.value-1)<=.011)
const normalizedWeight=key=>{const x=subsystems.value.find(v=>v.key===key);return rawWeightTotal.value?(Number(x.weight||0)/rawWeightTotal.value*100).toFixed(1):'0.0'},resetWeights=()=>subsystems.value.forEach(x=>x.weight=DEFAULT_WEIGHTS[x.key]),pct=v=>`${(Number(v)*100).toFixed(1)}%`,weightText=w=>Object.entries(w||{}).map(([k,v])=>`${k} ${(Number(v)*100).toFixed(1)}%`).join(' / ')
const modelResult=computed(()=>result.value?.algorithm_trace?.model_result),modelStatus=computed(()=>{const s=result.value?.algorithm_trace?.vae_gan_status;if(s==='evidence_only_uncalibrated')return'RF已校准量纲；VAE-GAN仅作证据';if(s==='inference_completed')return'训练模型推理完成';return`已回退：${result.value?.algorithm_trace?.model_error||'运行环境不可用'}`})
async function load(){const j=await(await fetch('/api/v1/phm/release-assessments/')).json();history.value=j.results||[]}
async function run(){if(!weightTotalValid.value)return ElMessage.warning('请将权重设置为合计100%');loading.value=true;try{const payload={...form.value,rul_margin:rulPercent.value/100,subsystem_health:Object.fromEntries(subsystems.value.map(x=>[x.key,x.percent/100])),subsystem_weights:Object.fromEntries(subsystems.value.map(x=>[x.key,Number(x.weight)]))};const r=await fetch('/api/v1/phm/release-assessments/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw Error(j.error);result.value=j.assessment;await load();ElMessage.success('放行评估已完成并留痕')}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}
onMounted(load)
</script>
<style scoped>.page{max-width:1320px}.head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:18px}.head span{font-size:12px;color:#1677ff;letter-spacing:1px}.head h2{margin:8px 0}.head p,.note,.hint,.param-help{color:#718198}.formula{margin-bottom:16px}.grid{display:grid;grid-template-columns:minmax(560px,1fr) minmax(480px,1fr);gap:18px}.hint{font-size:13px;line-height:1.7;margin:-8px 0 14px}.subsystem-row{padding:12px 0;border-bottom:1px solid #edf1f6}.subsystem-title{display:flex;align-items:center;gap:6px;margin-bottom:6px}.input-line{display:grid;grid-template-columns:58px minmax(0,1fr);align-items:center;gap:10px}.input-line>span{font-size:12px;color:#6a7b90}.weight-line{margin-top:6px;grid-template-columns:58px 150px 1fr}.weight-line small{color:#1677ff}.weight-summary{display:flex;justify-content:space-between;align-items:center;padding:12px 0}.ok{color:#16835b}.bad{color:#c43c3c}.param-help{font-size:12px;line-height:1.5;margin:-10px 0 12px 132px}.decision{padding:20px;border-radius:10px;margin-bottom:18px}.decision small,.decision strong,.decision span{display:block}.decision strong{font-size:30px;margin:8px 0}.decision.release{background:#ebf8f2;color:#16835b}.decision.hold{background:#fff0f0;color:#c43c3c}.el-progress{display:flex;justify-content:center;margin:16px}.el-alert{margin-top:16px}.history{margin-top:18px}@media(max-width:1050px){.grid{grid-template-columns:1fr}}@media(max-width:700px){.param-help{margin-left:0}.weight-line{grid-template-columns:52px 140px 1fr}}</style>
