<template>
<div class="telemetry">
 <header><h2>实时状态监测</h2><el-button @click="openSelector">选择数据源</el-button></header>
 <div class="toolbar"><el-tag>{{ mode === 'live' ? 'MATLAB 实时采集' : mode === 'replay' ? 'CSV 历史回放' : '未选择数据源' }}</el-tag><b>{{name}}</b><span>{{status}}</span>
  <template v-if="mode==='replay'"><el-button :disabled="busy||ended" @click="toggle">{{playing?'暂停回放':'开始回放'}}</el-button><el-button :disabled="busy" @click="reset">从头回放</el-button><el-select v-model="speed" class="speed"><el-option v-for="s in [1,2,5,10]" :key="s" :value="s" :label="`${s} 条/秒`"/></el-select></template>
  <el-button v-if="mode" :disabled="mode==='live'&&!total" @click="download">导出 CSV</el-button><el-button v-if="mode==='live'&&admin&&state!=='closed'" type="danger" plain @click="closeSession">结束采集</el-button>
 </div>
 <el-alert v-if="error" :title="error" type="error" :closable="false"/>
 <p v-if="mode">{{mode==='live'?'已采集':'已播放'}} {{total}} 条<span v-if="received"> · 最后接收 {{new Date(received).toLocaleString()}}</span></p>
 <el-empty v-if="!rows.length" :description="mode==='live'?'等待 MATLAB 上报数据':'请选择数据后开始回放'"/>
 <template v-else><div class="metrics"><div v-for="k in signals.slice(0,4)" :key="k"><small>{{k}}</small><strong>{{rows.at(-1)[k]??'—'}}</strong></div></div><div class="chart-title"><h3>信号趋势（最近 1000 条）</h3><el-select v-model="signal"><el-option v-for="k in signals" :key="k" :value="k" :label="k"/></el-select></div><ReportChart :option="chart"/><h3>最新采样</h3><el-table :data="rows.slice(-20).reverse()" stripe max-height="400"><el-table-column v-for="k in columns" :key="k" :prop="k" :label="k" min-width="130"/></el-table></template>
 <el-dialog v-model="selector" title="选择监测数据源" width="min(680px,94vw)" :close-on-click-modal="false">
  <el-radio-group v-model="choice"><el-radio-button label="replay">CSV 历史回放</el-radio-button><el-radio-button label="live">MATLAB 实时采集</el-radio-button></el-radio-group>
  <el-form label-position="top"><el-form-item v-if="choice==='replay'" label="选择一次仿真或离线上传的数据"><el-select v-model="datasetId" filterable><el-option v-for="d in datasets" :key="d.id" :value="d.id" :label="`${d.name} / ${d.source==='simulation'?'仿真':'离线'} / ${d.fault_type||'未标注'}`"/></el-select></el-form-item>
   <template v-else><el-alert title="实时采集操作流程" type="info" :closable="false" description="管理员先创建采集会话并复制令牌；在 MATLAB/Simulink 中调用 phm_send_telemetry 上报；回到异常告警中心选择同一会话并打开实时检测。"/><el-form-item label="采集会话"><div class="session-row"><el-select v-model="sessionId" filterable placeholder="请选择已有会话"><el-option v-for="s in sessions" :key="s.id" :value="s.id" :label="`${s.name} / ${labels[s.state]} / ${s.sample_count} 条`"/></el-select><el-button @click="refreshSessions">刷新</el-button></div></el-form-item><el-form-item v-if="admin" label="新建本次采集"><div class="session-row"><el-input v-model="sessionName" maxlength="200" placeholder="本次试验名称，如：发动机热试车-2026-09-16"/><el-button type="primary" :loading="creating" :disabled="!sessionName.trim()" @click="createSession">创建并获取 MATLAB 参数</el-button></div></el-form-item><el-alert v-if="!admin" title="当前账号为查看用户，不能创建采集会话；请联系管理员创建并提供会话。" type="warning" :closable="false"/></template>
  </el-form><el-alert v-if="error" :title="error" type="error" :closable="false"/>
  <template #footer><el-button @click="selector=false">取消</el-button><el-button type="primary" :disabled="choice==='replay'?!datasetId:!sessionId" @click="selectSource">{{choice==='replay'?'载入，等待播放':'查看实时采集'}}</el-button></template>
 </el-dialog>
 <el-dialog v-model="connectionDialog" title="MATLAB 实时接入操作说明" width="min(960px,96vw)" top="4vh" :close-on-click-modal="false" class="matlab-dialog">
  <el-alert title="请先保存本页令牌" type="warning" :closable="false" show-icon>采集令牌只在创建会话时显示一次。关闭弹窗前，请至少复制第 1 步代码；令牌失效或丢失后需要重新创建会话。</el-alert>
  <div class="matlab-summary"><b>完整演示流程</b><span>平台创建会话</span><i>→</i><span>MATLAB 配置连接</span><i>→</i><span>发送测试数据</span><i>→</i><span>运行故障演示</span><i>→</i><span>平台实时告警与诊断</span></div>

  <section class="guide-step">
   <div class="step-number">1</div><div class="step-content"><h3>复制连接配置，在 MATLAB 命令窗口执行</h3><p>这段代码会把平台提供的发送函数加入 MATLAB 路径，并保存本次会话的接收地址和令牌。项目在其他电脑时，请修改第一行目录。</p><div class="code-head"><span>MATLAB · 连接配置</span><el-button size="small" type="primary" plain @click="copyCode(matlabSetupCode,'连接配置')">复制代码</el-button></div><pre>{{matlabSetupCode}}</pre></div>
  </section>
  <section class="guide-step">
   <div class="step-number">2</div><div class="step-content"><h3>发送一条测试数据，确认连接成功</h3><p>继续在 MATLAB 命令窗口执行。正常时会显示平台返回结果，网页“实时状态监测”中的采样数会变为 1。</p><div class="code-head"><span>MATLAB · 单条连通测试</span><el-button size="small" type="primary" plain @click="copyCode(matlabTestCode,'测试代码')">复制代码</el-button></div><pre>{{matlabTestCode}}</pre></div>
  </section>
  <section class="guide-step">
   <div class="step-number">3</div><div class="step-content"><h3>在平台开启实时检测</h3><p>回到网页，进入左侧“状态监测 → 异常告警中心”，选择刚创建的会话并启用实时检测；然后返回 MATLAB 执行第 4 步。这样故障数据到达时，平台才会自动执行告警、诊断、隔离和健康评估。</p></div>
  </section>
  <section class="guide-step">
   <div class="step-number">4</div><div class="step-content"><h3>运行正常数据 → 压力故障的完整演示</h3><p>内置脚本会连续发送仿真数据，并在第 3 秒注入压力下降故障。MATLAB 命令窗口会显示每次接收和告警结果。</p><div class="code-head"><span>MATLAB · 实时故障注入演示</span><el-button size="small" type="primary" plain @click="copyCode(matlabDemoCode,'演示代码')">复制代码</el-button></div><pre>{{matlabDemoCode}}</pre></div>
  </section>
  <el-collapse class="advanced"><el-collapse-item title="接入自己的 MATLAB / Simulink 仿真（可选）"><p>在你的采样循环或 Simulink 回调中，将实际变量组成结构体后发送。time 必须递增，字段名在同一会话内保持一致。</p><div class="code-head"><span>MATLAB · 自定义仿真调用模板</span><el-button size="small" type="primary" plain @click="copyCode(connectionCode,'调用模板')">复制代码</el-button></div><pre>{{connectionCode}}</pre></el-collapse-item><el-collapse-item title="连接失败时检查"><ul><li>MATLAB 和平台在同一台电脑：地址保留 127.0.0.1。</li><li>MATLAB 在另一台电脑：把 127.0.0.1 改为平台电脑的局域网 IP，并确保 8000 端口可访问。</li><li>提示函数未定义：确认已执行第 1 步 addpath，并运行 <code>which phm_send_telemetry</code>。</li><li>提示令牌无效：该令牌可能复制不完整，请在平台重新创建采集会话。</li><li>重新从 time=0 开始仿真：请新建会话，旧会话不允许时间倒退。</li></ul></el-collapse-item></el-collapse>
  <template #footer><el-button @click="copyAllMatlab">复制全部 MATLAB 代码</el-button><el-button type="primary" @click="connectionDialog=false">我已保存，关闭</el-button></template>
 </el-dialog>
</div>
</template>
<script setup>
import {ref,computed,onMounted,onUnmounted} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import ReportChart from '../components/ReportChart.vue'
const datasets=ref([]),sessions=ref([]),datasetId=ref(null),sessionId=ref(null),admin=ref(false),sessionName=ref(''),creating=ref(false),LIVE_SOURCE_KEY='phm-live-source'
const selector=ref(true),choice=ref('replay'),mode=ref(''),id=ref(null),name=ref(''),rows=ref([]),columns=ref([]),signal=ref(''),playing=ref(false),ended=ref(false),busy=ref(false),speed=ref(1),error=ref(''),total=ref(0),received=ref(null),state=ref('waiting')
const connection=ref(null),connectionDialog=ref(false)
let timer,generation=0,offset=0,cursor=0,buffer=[],pos=0,more=true,shown=0
const labels={waiting:'等待数据',live:'正在接收',stale:'超过 5 秒未收到数据',closed:'采集已结束'}
const status=computed(()=>error.value?'读取失败':mode.value==='live'?labels[state.value]:ended.value?'回放结束':playing.value?'正在回放':'未播放')
const numeric=v=>v!==null&&v!==undefined&&String(v).trim()!==''&&Number.isFinite(Number(v))?Number(v):null
const timeKey=computed(()=>columns.value.find(k=>k.toLowerCase()==='time'))
const signals=computed(()=>columns.value.filter(k=>k!==timeKey.value&&rows.value.some(r=>numeric(r[k])!==null)))
const chart=computed(()=>({tooltip:{trigger:'axis'},grid:{containLabel:true,left:60,right:35,bottom:75},xAxis:{type:'value',name:timeKey.value||'样本序号'},yAxis:{type:'value',name:signal.value,scale:true},dataZoom:[{type:'inside'},{type:'slider'}],series:[{name:signal.value,type:'line',showSymbol:rows.value.length<2,symbolSize:8,connectNulls:false,data:rows.value.map((r,i)=>[timeKey.value?numeric(r[timeKey.value]):shown-rows.value.length+i,numeric(r[signal.value])])}]}))
const ingestUrl=computed(()=>connection.value?new URL(connection.value.ingest_path,location.origin).href:'')
const matlabSetupCode=computed(()=>connection.value?`% 第一次使用时执行：把平台 MATLAB 工具加入搜索路径\naddpath('E:/实验项目/航天管理项目/phm_platform/integrations/matlab');\naddpath('E:/实验项目/航天管理项目/phm_platform/integrations/matlab/examples');\n\n% 本次采集会话参数（请勿把 token 提交到代码仓库）\ningestUrl = '${ingestUrl.value}';\ntoken = '${connection.value.token}';\n\n% 检查发送函数是否可用\nassert(~isempty(which('phm_send_telemetry')), ...\n    '未找到 phm_send_telemetry.m，请检查上面的 addpath 路径');\ndisp('MATLAB 接入配置完成');`:'')
const matlabTestCode=computed(()=>`% 发送 1 条正常测试数据\ntestSample = struct( ...\n    'time', 0, ...\n    'pressure', 10.0, ...\n    'temperature', 25.0);\n\nresponse = phm_send_telemetry(ingestUrl, token, testSample);\ndisp(response);`)
const matlabDemoCode=computed(()=>`% 运行内置实时故障注入演示（默认约 2 分钟、241 条数据）\n% 0~3 秒发送正常数据，3 秒后注入压力下降故障\nfaultStartTime = 3.0;\nduration = 60.0;       % 仿真时长（秒），可改为 300 等更长时间\nsamplePeriod = 0.25;   % 采样周期（秒），越小数据越密集\nresponses = demo_realtime_fault_injection( ...\n    ingestUrl, token, faultStartTime, duration, samplePeriod);\n\ndisp('演示发送完成，请回到平台查看告警、诊断和健康评估结果');`)
const connectionCode=computed(()=>`% 放入你自己的 MATLAB / Simulink 采样循环或回调中\nsample = struct( ...\n    'time', t, ...\n    'pressure', pressure, ...\n    'temperature', temperature);\nresponse = phm_send_telemetry(ingestUrl, token, sample);`)
async function api(url,body){const token=document.cookie.split('; ').find(x=>x.startsWith('csrftoken='))?.slice(10);const r=await fetch(url,{credentials:'include',...(body!==undefined?{method:'POST',headers:{'Content-Type':'application/json',...(token?{'X-CSRFToken':decodeURIComponent(token)}:{})},body:JSON.stringify(body)}:{})});const j=await r.json();if(!r.ok)throw Error(j.detail||j.error||`请求失败 ${r.status}`);return j}
async function choices(){datasets.value=await api('/api/v1/datasets/');await refreshSessions()}
async function refreshSessions(){sessions.value=await api('/api/v1/phm/telemetry/sessions/');if(!sessionId.value&&sessions.value.length)sessionId.value=sessions.value[0].id}
async function openSelector(){selector.value=true;try{await choices()}catch(e){error.value=e.message}}
function reset(){clearTimeout(timer);generation++;rows.value=[];columns.value=[];signal.value='';playing.value=false;ended.value=false;busy.value=false;error.value='';offset=0;cursor=0;buffer=[];pos=0;more=true;total.value=0;shown=0;received.value=null;state.value='waiting'}
function persistLiveSource(){if(mode.value==='live'&&id.value)localStorage.setItem(LIVE_SOURCE_KEY,JSON.stringify({id:id.value,name:name.value}))}
function selectSource(){reset();mode.value=choice.value;id.value=mode.value==='replay'?datasetId.value:sessionId.value;name.value=(mode.value==='replay'?datasets.value:sessions.value).find(x=>x.id===id.value)?.name||'';selector.value=false;if(mode.value==='live'){persistLiveSource();poll(generation)}}
function append(batch){shown+=batch.length;rows.value=[...rows.value,...batch].slice(-1000);if(!signals.value.includes(signal.value))signal.value=signals.value[0]||''}
async function step(g){if(g!==generation||!playing.value)return;busy.value=true;try{if(pos>=buffer.length&&more){const j=await api(`/api/v1/datasets/${id.value}/samples/?offset=${offset}&limit=500`);if(g!==generation)return;columns.value=j.columns;buffer=j.rows;pos=0;offset=j.next_offset;more=j.has_more}if(g!==generation||!playing.value)return;if(pos<buffer.length){append([buffer[pos++]]);total.value++}if(pos>=buffer.length&&!more){ended.value=true;playing.value=false;return}timer=setTimeout(()=>step(g),1000/speed.value)}catch(e){if(g===generation){error.value=e.message;playing.value=false}}finally{if(g===generation)busy.value=false}}
function toggle(){clearTimeout(timer);playing.value=!playing.value;if(playing.value){error.value='';step(generation)}}
async function poll(g){try{const j=await api(`/api/v1/phm/telemetry/sessions/${id.value}/samples/?after=${cursor}&limit=500`);if(g!==generation)return;columns.value=j.columns;cursor=j.next_cursor;append(j.rows);total.value=j.sample_count;received.value=j.last_received_at;state.value=j.state;error.value='';if(j.has_more||j.state!=='closed')timer=setTimeout(()=>poll(g),j.has_more?30:1000)}catch(e){if(g===generation){error.value=e.message;timer=setTimeout(()=>poll(g),3000)}}}
async function createSession(){creating.value=true;try{connection.value=await api('/api/v1/phm/telemetry/sessions/',{name:sessionName.value});sessionId.value=connection.value.id;connectionDialog.value=true;sessions.value=await api('/api/v1/phm/telemetry/sessions/');localStorage.setItem(LIVE_SOURCE_KEY,JSON.stringify({id:connection.value.id,name:sessionName.value}))}catch(e){error.value=e.message}finally{creating.value=false}}
async function closeSession(){try{await ElMessageBox.confirm('结束后本会话不再接收数据，仍可导出已采集的 CSV。','结束采集',{type:'warning'});await api(`/api/v1/phm/telemetry/sessions/${id.value}/close/`,{});clearTimeout(timer);generation++;poll(generation)}catch(e){if(e!=='cancel'&&e!=='close')error.value=e.message}}
async function copyCode(code,label='代码'){try{await navigator.clipboard.writeText(code);ElMessage.success(`${label}已复制，可粘贴到 MATLAB 命令窗口执行`)}catch{ElMessage.error('自动复制失败，请手动选中代码复制')}}
async function copyAllMatlab(){const all=`%% 第 1 步：连接配置\n${matlabSetupCode.value}\n\n%% 第 2 步：连通测试\n${matlabTestCode.value}\n\n%% 第 4 步：实时故障演示\n${matlabDemoCode.value}`;await copyCode(all,'全部 MATLAB 代码')}
function download(){window.open(mode.value==='replay'?`/api/v1/datasets/${id.value}/download/`:`/api/v1/phm/telemetry/sessions/${id.value}/export/`,'_blank')}
onMounted(async()=>{try{admin.value=(await api('/api/v1/permissions/profile/')).role==='admin';await choices();const saved=JSON.parse(localStorage.getItem(LIVE_SOURCE_KEY)||'null');const found=saved&&sessions.value.find(s=>s.id===saved.id);if(found){choice.value='live';sessionId.value=found.id;mode.value='live';id.value=found.id;name.value=found.name;selector.value=false;poll(generation)}}catch(e){error.value=e.message}})
onUnmounted(()=>{generation++;clearTimeout(timer)})
</script>
<style scoped>
.telemetry{max-width:1400px;min-width:0}header,.toolbar,.chart-title,.session-row{display:flex;align-items:center;gap:12px;flex-wrap:wrap}header,.chart-title{justify-content:space-between}.toolbar{padding:16px 0;border-bottom:1px solid #dde4ed}.speed{width:120px}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:20px;margin:24px 0}.metrics small,.metrics strong{display:block;overflow-wrap:anywhere}.metrics strong{font-size:24px;margin-top:8px}.chart-title .el-select{width:260px}.el-form{margin-top:24px}.el-form .el-select{width:100%}.session-row .el-select,.session-row .el-input{flex:1;min-width:220px}.el-alert{margin:12px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;padding:16px;background:#152234;color:#d9e7f5;border-radius:0 0 6px 6px;margin:0;font:13px/1.65 Consolas,'Courier New',monospace}p{color:#627080;line-height:1.7}.matlab-summary{display:flex;align-items:center;gap:10px;flex-wrap:wrap;padding:14px 16px;margin:16px 0;background:#f1f7ff;border:1px solid #cfe2ff;border-radius:6px;color:#315d8e}.matlab-summary span{background:#fff;padding:6px 10px;border-radius:4px}.matlab-summary i{font-style:normal;color:#409eff}.guide-step{display:grid;grid-template-columns:38px minmax(0,1fr);gap:14px;padding:18px 0;border-bottom:1px solid #e6ebf2}.step-number{width:32px;height:32px;display:grid;place-items:center;border-radius:50%;background:#1677ff;color:#fff;font-weight:700}.step-content h3{margin:4px 0 6px;color:#25364d}.step-content p{margin:0 0 12px}.code-head{display:flex;align-items:center;justify-content:space-between;padding:8px 10px;background:#e4ebf3;border-radius:6px 6px 0 0;color:#40556d;font-size:13px;font-weight:600}.advanced{margin-top:16px}.advanced ul{color:#627080;line-height:1.9}.advanced code{background:#edf2f7;padding:2px 5px;border-radius:3px}@media(max-width:700px){.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.guide-step{grid-template-columns:1fr}.matlab-summary i{display:none}}
</style>
